# Generated by Django 5.2.7 on 2025-11-14 13:37

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('client_secret', models.CharField(default=secrets.token_urlsafe, max_length=128)),
                ('redirect_uris', models.TextField(help_text='Danh sách URI, phân cách bằng dấu xuống dòng')),
                ('scopes', models.CharField(help_text='Phạm vi truy cập, phân cách bằng dấu cách', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
